name: hypha_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.17+54

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # UI and Navigation
  get: ^4.6.5

  # State Management
  flutter_bloc: ^8.1.3

  # Logging
  fimber: ^0.6.6

  # Helper Collections
  collection: ^1.16.0

  # Generated Code
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  build_runner: ^2.3.2

  # Async Code. Cancellable futures, etc
  async: ^2.9.0

  # Pretty dates and times
  timeago: ^3.4.0

  # equality
  equatable: ^2.0.5

  # Shared Pref
  shared_preferences: ^2.0.15

  # QR code Scanner
  mobile_scanner: ^3.4.1

  # RX-ify Shared Preferences
  rx_shared_preferences: ^3.0.0

  # DI
  get_it: ^7.2.0

  # Crypto
  pointycastle: ^3.6.2
  bs58check: ^1.0.2
  hdkey: ^0.0.1

  # Json Serial
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # image picker
  image_picker: ^0.8.6

  # Network
  dio: ^5.3.0
  # Retry failed calls
  dio_smart_retry: ^5.0.0
  # API Logs in Terminal
  pretty_dio_logger: ^1.3.1

  # App Permissions
  permission_handler: ^10.2.0

  # Share
  share_plus: ^7.0.0

  # Launch URL
  url_launcher: ^6.1.12

  # Fonts
  google_fonts: ^4.0.4

  # formatting
  intl: ^0.18.0

  flutter_svg: ^2.0.5

  # encrypt stored data
  flutter_secure_storage: ^8.0.0

  # Crop image after selecting it from picker
  image_cropper: ^4.0.1

  # Firebase
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.9.1
  firebase_analytics: ^10.4.5
  firebase_remote_config: ^4.2.5

  # Amazon stuff for profile... Weak sauce
  amazon_cognito_identity_dart_2: ^3.2.0
  app_links: ^3.4.3

  # Dotted outline container
  dotted_border: ^2.0.0+3

  # Get the app version
  package_info_plus: ^4.0.2

  # Animations
  lottie: ^2.5.0

  # Load images and files from IPFS
  ipfs_client_flutter: ^1.0.7

  # Env variables
  flutter_dotenv: ^5.1.0

  icons_launcher: ^2.1.3

dependency_overrides:
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      # Do Android in Android studio. 
      # 1. Right click on app->res->mipmap, 
      # 2. select "New Image Asset"
      # 3. Create a launcher asset
      enable: false
    ios:
      enable: true
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - assets/images/graphics/
   - assets/images/logos/hypha_logo.svg
   - assets/images/logos/hypha_logo_composite.svg
   - assets/images/signout.png
   - assets/images/warning.png
   - assets/images/thumb_up.png
   - assets/images/shield.png
   - assets/images/logos/dark/hypha_logo_composite.svg
   - assets/config/profile_service/config.json
   - assets/animations/hypha_splash.json
   - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: HyphaIcons
      fonts:
        - asset: assets/fonts/HyphaIcons.ttf
